- name: Configure application
  hosts: all
  become: true
  become_method: sudo

  tasks:

    - name: Install python3
      apt:
        name: python3-pip
        state: latest
        update-cache: yes

    - name: Install git
      apt:
        name: git
        state: latest
        update-cache: yes

    - name: Install xfce4
      apt:
        name: xfce4
        state: latest
        update-cache: yes

    - name: Start xfce4
      shell: startx

    # - name: Pip install numpy
    #   pip:
    #     executable: pip3
    #     name:
    #       - numpy

    # - name: Copy Python script to virtual machine
    #   copy:
    #     src: monte-carlo-sim
    #     dest: /home/vagrant/
    #     force: yes

    # - name: Run Python monte-carlo-sim
    #   shell: python3 /home/vagrant/monte-carlo-sim/monte_carlo_sim.py
